services:
  mariadb-server:
    image: ghcr.io/podmania/mariadb-server:latest
    # set to host user id and gid
    # defaults to 1000:1000
    # user: 1001:1001
    container_name: mariadb-server
    ports:
      - 3306:3306
    volumes:   
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro # optional: use either TZ variable or localtime mapping, not both
    # environment:
    #   - TZ=America/New_York
    restart: unless-stopped
volumes:
  db:
